// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260302131854_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Model.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "1CHIT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "2CHIT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "3CHIT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "4CHIT"
                        },
                        new
                        {
                            Id = 5,
                            Name = "5CHIT"
                        });
                });

            modelBuilder.Entity("Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IT Krems",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "IT Zwettl",
                            SchoolId = 1
                        });
                });

            modelBuilder.Entity("Model.Pupil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Pupils");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lukas Huber"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sarah Maier"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Maximilian Gruber"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Julia Pichler"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Felix Müller"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Emma Wagner"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tobias Berger"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Anna Fuchs"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Moritz Hofer"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Elena Steiner"
                        });
                });

            modelBuilder.Entity("Model.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HTL Krems"
                        });
                });

            modelBuilder.Entity("Model.Department", b =>
                {
                    b.HasOne("Model.School", "School")
                        .WithMany("Departments")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Model.Pupil", b =>
                {
                    b.HasOne("Model.Class", "Class")
                        .WithMany("Pupils")
                        .HasForeignKey("ClassId");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Model.Class", b =>
                {
                    b.Navigation("Pupils");
                });

            modelBuilder.Entity("Model.School", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
