// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(StundenplanContext))]
    [Migration("20260323132105_Migration3")]
    partial class Migration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Model.ClassSubject", b =>
                {
                    b.Property<int>("Cid")
                        .HasColumnType("int");

                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.HasKey("Cid", "Sid");

                    b.HasIndex("Sid");

                    b.ToTable("ClassSubjects");

                    b.HasData(
                        new
                        {
                            Cid = 1,
                            Sid = 18
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 18
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 9
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 19
                        },
                        new
                        {
                            Cid = 5,
                            Sid = 19
                        });
                });

            modelBuilder.Entity("Model.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cid")
                        .HasColumnType("int");

                    b.Property<int?>("Hour")
                        .HasColumnType("int");

                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.Property<int>("Tid")
                        .HasColumnType("int");

                    b.Property<int>("WeekDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cid", "Sid");

                    b.HasIndex("Tid", "Sid");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 203,
                            Cid = 1,
                            Hour = 1,
                            Sid = 18,
                            Tid = 1,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 299,
                            Cid = 4,
                            Hour = 2,
                            Sid = 18,
                            Tid = 1,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 378,
                            Cid = 4,
                            Hour = 3,
                            Sid = 9,
                            Tid = 13,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 379,
                            Cid = 4,
                            Hour = 4,
                            Sid = 19,
                            Tid = 13,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 399,
                            Cid = 5,
                            Hour = 5,
                            Sid = 19,
                            Tid = 13,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 1277,
                            Cid = 5,
                            Hour = 6,
                            Sid = 19,
                            Tid = 2,
                            WeekDay = 1
                        });
                });

            modelBuilder.Entity("Model.SchoolClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbr = "1CHIT"
                        },
                        new
                        {
                            Id = 2,
                            Abbr = "2CHIT"
                        },
                        new
                        {
                            Id = 3,
                            Abbr = "3CHIT"
                        },
                        new
                        {
                            Id = 4,
                            Abbr = "4CHIT"
                        },
                        new
                        {
                            Id = 5,
                            Abbr = "5CHIT"
                        });
                });

            modelBuilder.Entity("Model.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "AM"
                        },
                        new
                        {
                            Id = 4,
                            Desc = "D"
                        },
                        new
                        {
                            Id = 5,
                            Desc = "E"
                        },
                        new
                        {
                            Id = 9,
                            Desc = "INSY"
                        },
                        new
                        {
                            Id = 18,
                            Desc = "REL"
                        },
                        new
                        {
                            Id = 19,
                            Desc = "SEW"
                        },
                        new
                        {
                            Id = 20,
                            Desc = "SOPK"
                        },
                        new
                        {
                            Id = 21,
                            Desc = "SYT"
                        });
                });

            modelBuilder.Entity("Model.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbr = "ALLI"
                        },
                        new
                        {
                            Id = 2,
                            Abbr = "BIRN"
                        },
                        new
                        {
                            Id = 13,
                            Abbr = "MACO"
                        },
                        new
                        {
                            Id = 14,
                            Abbr = "NIGI"
                        },
                        new
                        {
                            Id = 19,
                            Abbr = "STRO"
                        });
                });

            modelBuilder.Entity("Model.TeacherSubject", b =>
                {
                    b.Property<int>("Tid")
                        .HasColumnType("int");

                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.HasKey("Tid", "Sid");

                    b.HasIndex("Sid");

                    b.ToTable("TeacherSubjects");

                    b.HasData(
                        new
                        {
                            Tid = 1,
                            Sid = 18
                        },
                        new
                        {
                            Tid = 13,
                            Sid = 9
                        },
                        new
                        {
                            Tid = 13,
                            Sid = 19
                        },
                        new
                        {
                            Tid = 2,
                            Sid = 19
                        });
                });

            modelBuilder.Entity("Model.ClassSubject", b =>
                {
                    b.HasOne("Model.SchoolClass", "SchoolClass")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("Cid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("Sid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolClass");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Model.Lesson", b =>
                {
                    b.HasOne("Model.ClassSubject", "ClassSubject")
                        .WithMany()
                        .HasForeignKey("Cid", "Sid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.TeacherSubject", "TeacherSubject")
                        .WithMany()
                        .HasForeignKey("Tid", "Sid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassSubject");

                    b.Navigation("TeacherSubject");
                });

            modelBuilder.Entity("Model.TeacherSubject", b =>
                {
                    b.HasOne("Model.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("Sid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("Tid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Model.SchoolClass", b =>
                {
                    b.Navigation("ClassSubjects");
                });

            modelBuilder.Entity("Model.Teacher", b =>
                {
                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
