// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(StundenplanContext))]
    [Migration("20260219102101_Migration1")]
    partial class Migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ClassesSubjects", b =>
                {
                    b.Property<int>("CId")
                        .HasColumnType("int");

                    b.Property<int>("SId")
                        .HasColumnType("int");

                    b.HasKey("CId", "SId");

                    b.HasIndex("SId");

                    b.ToTable("ClassesSubjects");

                    b.HasData(
                        new
                        {
                            CId = 5,
                            SId = 2
                        },
                        new
                        {
                            CId = 5,
                            SId = 3
                        },
                        new
                        {
                            CId = 1,
                            SId = 2
                        });
                });

            modelBuilder.Entity("Model.Classes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "1CHIT"
                        },
                        new
                        {
                            Id = 2,
                            Description = "2CHIT"
                        },
                        new
                        {
                            Id = 3,
                            Description = "3CHIT"
                        },
                        new
                        {
                            Id = 4,
                            Description = "4CHIT"
                        },
                        new
                        {
                            Id = 5,
                            Description = "5CHIT"
                        });
                });

            modelBuilder.Entity("Model.Subjects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "AM"
                        },
                        new
                        {
                            Id = 2,
                            Description = "SEW"
                        },
                        new
                        {
                            Id = 3,
                            Description = "INSY"
                        },
                        new
                        {
                            Id = 4,
                            Description = "D"
                        },
                        new
                        {
                            Id = 5,
                            Description = "E"
                        });
                });

            modelBuilder.Entity("ClassesSubjects", b =>
                {
                    b.HasOne("Model.Classes", null)
                        .WithMany()
                        .HasForeignKey("CId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Subjects", null)
                        .WithMany()
                        .HasForeignKey("SId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
