// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(StundenplanContext))]
    partial class StundenplanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Model.ClassSubject", b =>
                {
                    b.Property<int>("Cid")
                        .HasColumnType("int");

                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.HasKey("Cid", "Sid");

                    b.HasIndex("Sid");

                    b.ToTable("ClassSubjects");

                    b.HasData(
                        new
                        {
                            Cid = 4,
                            Sid = 1
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 2
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 3
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 4
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 5
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 6
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 7
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 8
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 9
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 10
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 11
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 12
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 13
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 14
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 15
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 16
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 17
                        },
                        new
                        {
                            Cid = 4,
                            Sid = 18
                        });
                });

            modelBuilder.Entity("Model.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cid")
                        .HasColumnType("int");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.Property<int>("Tid")
                        .HasColumnType("int");

                    b.Property<int>("WeekDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cid", "Sid");

                    b.HasIndex("Tid", "Sid");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cid = 4,
                            Hour = 1,
                            Sid = 5,
                            Tid = 1,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 2,
                            Cid = 4,
                            Hour = 2,
                            Sid = 13,
                            Tid = 7,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 3,
                            Cid = 4,
                            Hour = 3,
                            Sid = 13,
                            Tid = 7,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 4,
                            Cid = 4,
                            Hour = 4,
                            Sid = 5,
                            Tid = 1,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 5,
                            Cid = 4,
                            Hour = 5,
                            Sid = 16,
                            Tid = 12,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 6,
                            Cid = 4,
                            Hour = 7,
                            Sid = 10,
                            Tid = 5,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 7,
                            Cid = 4,
                            Hour = 8,
                            Sid = 6,
                            Tid = 2,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 8,
                            Cid = 4,
                            Hour = 9,
                            Sid = 6,
                            Tid = 2,
                            WeekDay = 1
                        },
                        new
                        {
                            Id = 9,
                            Cid = 4,
                            Hour = 1,
                            Sid = 8,
                            Tid = 4,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 10,
                            Cid = 4,
                            Hour = 2,
                            Sid = 14,
                            Tid = 8,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 11,
                            Cid = 4,
                            Hour = 3,
                            Sid = 2,
                            Tid = 4,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 12,
                            Cid = 4,
                            Hour = 4,
                            Sid = 2,
                            Tid = 4,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 13,
                            Cid = 4,
                            Hour = 5,
                            Sid = 17,
                            Tid = 13,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 14,
                            Cid = 4,
                            Hour = 7,
                            Sid = 14,
                            Tid = 8,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 15,
                            Cid = 4,
                            Hour = 8,
                            Sid = 14,
                            Tid = 8,
                            WeekDay = 2
                        },
                        new
                        {
                            Id = 16,
                            Cid = 4,
                            Hour = 1,
                            Sid = 9,
                            Tid = 3,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 17,
                            Cid = 4,
                            Hour = 2,
                            Sid = 15,
                            Tid = 9,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 18,
                            Cid = 4,
                            Hour = 3,
                            Sid = 3,
                            Tid = 10,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 19,
                            Cid = 4,
                            Hour = 4,
                            Sid = 7,
                            Tid = 11,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 20,
                            Cid = 4,
                            Hour = 5,
                            Sid = 7,
                            Tid = 11,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 21,
                            Cid = 4,
                            Hour = 6,
                            Sid = 15,
                            Tid = 9,
                            WeekDay = 3
                        },
                        new
                        {
                            Id = 22,
                            Cid = 4,
                            Hour = 1,
                            Sid = 11,
                            Tid = 5,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 23,
                            Cid = 4,
                            Hour = 2,
                            Sid = 4,
                            Tid = 2,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 24,
                            Cid = 4,
                            Hour = 3,
                            Sid = 4,
                            Tid = 2,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 25,
                            Cid = 4,
                            Hour = 4,
                            Sid = 4,
                            Tid = 2,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 26,
                            Cid = 4,
                            Hour = 5,
                            Sid = 4,
                            Tid = 2,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 27,
                            Cid = 4,
                            Hour = 6,
                            Sid = 6,
                            Tid = 2,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 28,
                            Cid = 4,
                            Hour = 8,
                            Sid = 18,
                            Tid = 14,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 29,
                            Cid = 4,
                            Hour = 9,
                            Sid = 18,
                            Tid = 14,
                            WeekDay = 4
                        },
                        new
                        {
                            Id = 30,
                            Cid = 4,
                            Hour = 1,
                            Sid = 12,
                            Tid = 6,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 31,
                            Cid = 4,
                            Hour = 2,
                            Sid = 12,
                            Tid = 6,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 32,
                            Cid = 4,
                            Hour = 3,
                            Sid = 13,
                            Tid = 7,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 33,
                            Cid = 4,
                            Hour = 4,
                            Sid = 3,
                            Tid = 10,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 34,
                            Cid = 4,
                            Hour = 5,
                            Sid = 1,
                            Tid = 3,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 35,
                            Cid = 4,
                            Hour = 6,
                            Sid = 1,
                            Tid = 3,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 36,
                            Cid = 4,
                            Hour = 8,
                            Sid = 17,
                            Tid = 6,
                            WeekDay = 5
                        },
                        new
                        {
                            Id = 37,
                            Cid = 4,
                            Hour = 9,
                            Sid = 17,
                            Tid = 6,
                            WeekDay = 5
                        });
                });

            modelBuilder.Entity("Model.SchoolClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Abbr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbr = 1
                        },
                        new
                        {
                            Id = 2,
                            Abbr = 2
                        },
                        new
                        {
                            Id = 3,
                            Abbr = 3
                        },
                        new
                        {
                            Id = 4,
                            Abbr = 4
                        },
                        new
                        {
                            Id = 5,
                            Abbr = 5
                        });
                });

            modelBuilder.Entity("Model.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Desc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = 0
                        },
                        new
                        {
                            Id = 2,
                            Desc = 1
                        },
                        new
                        {
                            Id = 3,
                            Desc = 2
                        },
                        new
                        {
                            Id = 4,
                            Desc = 3
                        },
                        new
                        {
                            Id = 5,
                            Desc = 4
                        },
                        new
                        {
                            Id = 6,
                            Desc = 5
                        },
                        new
                        {
                            Id = 7,
                            Desc = 6
                        },
                        new
                        {
                            Id = 8,
                            Desc = 7
                        },
                        new
                        {
                            Id = 9,
                            Desc = 8
                        },
                        new
                        {
                            Id = 10,
                            Desc = 9
                        },
                        new
                        {
                            Id = 11,
                            Desc = 10
                        },
                        new
                        {
                            Id = 12,
                            Desc = 11
                        },
                        new
                        {
                            Id = 13,
                            Desc = 12
                        },
                        new
                        {
                            Id = 14,
                            Desc = 13
                        },
                        new
                        {
                            Id = 15,
                            Desc = 14
                        },
                        new
                        {
                            Id = 16,
                            Desc = 15
                        },
                        new
                        {
                            Id = 17,
                            Desc = 16
                        },
                        new
                        {
                            Id = 18,
                            Desc = 17
                        });
                });

            modelBuilder.Entity("Model.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Abbr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbr = 0
                        },
                        new
                        {
                            Id = 2,
                            Abbr = 1
                        },
                        new
                        {
                            Id = 3,
                            Abbr = 2
                        },
                        new
                        {
                            Id = 4,
                            Abbr = 3
                        },
                        new
                        {
                            Id = 5,
                            Abbr = 4
                        },
                        new
                        {
                            Id = 6,
                            Abbr = 5
                        },
                        new
                        {
                            Id = 7,
                            Abbr = 6
                        },
                        new
                        {
                            Id = 8,
                            Abbr = 7
                        },
                        new
                        {
                            Id = 9,
                            Abbr = 8
                        },
                        new
                        {
                            Id = 10,
                            Abbr = 9
                        },
                        new
                        {
                            Id = 11,
                            Abbr = 10
                        },
                        new
                        {
                            Id = 12,
                            Abbr = 11
                        },
                        new
                        {
                            Id = 13,
                            Abbr = 12
                        },
                        new
                        {
                            Id = 14,
                            Abbr = 13
                        });
                });

            modelBuilder.Entity("Model.TeacherSubject", b =>
                {
                    b.Property<int>("Tid")
                        .HasColumnType("int");

                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.HasKey("Tid", "Sid");

                    b.HasIndex("Sid");

                    b.ToTable("TeacherSubjects");

                    b.HasData(
                        new
                        {
                            Tid = 1,
                            Sid = 5
                        },
                        new
                        {
                            Tid = 7,
                            Sid = 13
                        },
                        new
                        {
                            Tid = 12,
                            Sid = 16
                        },
                        new
                        {
                            Tid = 5,
                            Sid = 10
                        },
                        new
                        {
                            Tid = 5,
                            Sid = 11
                        },
                        new
                        {
                            Tid = 2,
                            Sid = 6
                        },
                        new
                        {
                            Tid = 2,
                            Sid = 4
                        },
                        new
                        {
                            Tid = 4,
                            Sid = 8
                        },
                        new
                        {
                            Tid = 4,
                            Sid = 2
                        },
                        new
                        {
                            Tid = 8,
                            Sid = 14
                        },
                        new
                        {
                            Tid = 13,
                            Sid = 17
                        },
                        new
                        {
                            Tid = 3,
                            Sid = 9
                        },
                        new
                        {
                            Tid = 9,
                            Sid = 15
                        },
                        new
                        {
                            Tid = 10,
                            Sid = 3
                        },
                        new
                        {
                            Tid = 11,
                            Sid = 7
                        },
                        new
                        {
                            Tid = 14,
                            Sid = 18
                        },
                        new
                        {
                            Tid = 6,
                            Sid = 12
                        },
                        new
                        {
                            Tid = 6,
                            Sid = 17
                        },
                        new
                        {
                            Tid = 3,
                            Sid = 1
                        });
                });

            modelBuilder.Entity("Model.ClassSubject", b =>
                {
                    b.HasOne("Model.SchoolClass", "SchoolClass")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("Cid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("Sid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolClass");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Model.Lesson", b =>
                {
                    b.HasOne("Model.ClassSubject", "ClassSubject")
                        .WithMany()
                        .HasForeignKey("Cid", "Sid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.TeacherSubject", "TeacherSubject")
                        .WithMany()
                        .HasForeignKey("Tid", "Sid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassSubject");

                    b.Navigation("TeacherSubject");
                });

            modelBuilder.Entity("Model.TeacherSubject", b =>
                {
                    b.HasOne("Model.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("Sid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("Tid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Model.SchoolClass", b =>
                {
                    b.Navigation("ClassSubjects");
                });

            modelBuilder.Entity("Model.Teacher", b =>
                {
                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
