// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Context;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260309133230_Change to TPT")]
    partial class ChangetoTPT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Model.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Recorded")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Model.Bird", b =>
                {
                    b.HasBaseType("Model.Animal");

                    b.Property<string>("Wingspan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Birds", (string)null);
                });

            modelBuilder.Entity("Model.Dog", b =>
                {
                    b.HasBaseType("Model.Animal");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Dogs", (string)null);
                });

            modelBuilder.Entity("Model.Bird", b =>
                {
                    b.HasOne("Model.Animal", null)
                        .WithOne()
                        .HasForeignKey("Model.Bird", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Dog", b =>
                {
                    b.HasOne("Model.Animal", null)
                        .WithOne()
                        .HasForeignKey("Model.Dog", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
