// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Context;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260305092124_HasValue")]
    partial class HasValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Model.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Recorded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("animal_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasDiscriminator<string>("animal_type").HasValue("Common_animal");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Model.Bird", b =>
                {
                    b.HasBaseType("Model.Animal");

                    b.Property<string>("Wingspan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Beep");
                });

            modelBuilder.Entity("Model.Dog", b =>
                {
                    b.HasBaseType("Model.Animal");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Wauwau");
                });
#pragma warning restore 612, 618
        }
    }
}
